import { expect, test } from '@playwright/test'

test('Host uploads before opening and Attendee reads the same room material', async ({ page, browser }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: '함께할 준비를 해요' })).toBeVisible()
  await page.getByLabel('참여 이름', { exact: true }).fill('자료 Host')
  await page.getByLabel('미팅룸 이름', { exact: true }).fill('에이전트 연결 미팅')
  await page.getByLabel('발표 자료 업로드').setInputFiles({
    name: 'meeting-notes.txt', mimeType: 'text/plain', buffer: Buffer.from('Agent input: hello team!'),
  })
  await expect(page.locator('.join-file-list')).toContainText('meeting-notes.txt')
  await page.getByRole('button', { name: 'Host로 방 열기' }).click()
  await expect(page.getByRole('heading', { name: '에이전트 연결 미팅' })).toBeVisible()
  await expect(page.getByTestId('connection-status')).toHaveText('실시간 연결')
  await expect(page.locator('.participant-role-badge')).toHaveText('Host')
  await page.getByRole('button', { name: '자료 1', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('meeting-notes.txt')
  await page.getByRole('button', { name: '닫기', exact: true }).click()
  const attendee = await browser.newPage()
  try {
    await attendee.goto(page.url())
    await expect(attendee.getByRole('radio', { name: /Attendee/ })).toBeChecked()
    await attendee.getByLabel('참여 이름', { exact: true }).fill('팀원')
    await attendee.getByRole('button', { name: 'Attendee로 입장' }).click()
    await expect(attendee.locator('.participant-role-badge')).toHaveText('Attendee')
    await attendee.getByRole('button', { name: '자료 1', exact: true }).click()
    const download = attendee.waitForEvent('download')
    await attendee.getByRole('button', { name: 'meeting-notes.txt 다운로드' }).click()
    expect((await download).suggestedFilename()).toBe('meeting-notes.txt')
    await attendee.getByRole('button', { name: '닫기', exact: true }).click()
    await expect(attendee.getByRole('button', { name: '화면 공유', exact: true })).toHaveCount(0)
  } finally { await attendee.close() }
})

test('Attendee cannot create a missing room; landing fits mobile', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/?room=missing-onboarding-room')
  await page.getByRole('button', { name: 'Attendee로 입장' }).click()
  await expect(page.getByRole('alert')).toContainText('열리지 않았거나 종료된 방')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('team mascot and eight sample attendees appear in each new real room', async ({ page, browser }) => {
  await page.goto('/')
  await expect(page.getByRole('img', { name: '모여극장 로고', exact: true })).toBeVisible()
  await expect.poll(() => page.locator('.join-mascot img').evaluate((image) =>
    (image as HTMLImageElement).naturalWidth)).toBe(1024)
  await expect(page.locator('link[rel="icon"]')).toHaveAttribute('href', '/team-logo.png')
  await page.screenshot({ path: 'test-results\\team-logo-desktop.png', fullPage: true })
  for (const width of [390, 320]) {
    await page.setViewportSize({ width, height: 844 })
    await expect(page.locator('.join-mascot img')).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  }
  await page.screenshot({ path: 'test-results\\team-logo-mobile.png', fullPage: true })
  await page.setViewportSize({ width: 1440, height: 960 })
  await page.getByRole('button', { name: 'Host로 방 열기' }).click()
  await expect(page.getByTestId('connection-status')).toHaveText('실시간 연결')
  await expect(page.locator('.room-capacity')).toContainText('실제 참여 1명 · 예시 관객 8명')
  await expect(page.locator('.theater-seat.occupied')).toHaveCount(8)
  await expect(page.getByTestId('question-card')).toHaveCount(3)
  await expect(page.getByTestId('question-card').locator('.example-label')).toHaveCount(3)
  await expect(page.getByTestId('question-bubble')).toHaveCount(0)
  await expect(page.getByRole('complementary', { name: '스페이스 메뉴' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'AI 질문 도우미 열기' })).toBeVisible()
  await expect(page.locator('.header-brand .team-logo')).toHaveAttribute('src', '/team-logo.png')
  await page.screenshot({ path: 'test-results\\room-with-team-logo.png', fullPage: true })
  await page.getByRole('tab', { name: /참여자/ }).click()
  await expect(page.getByTestId('person-row')).toHaveCount(9)
  const attendee = await browser.newPage()
  try {
    await attendee.goto(page.url())
    await attendee.getByRole('button', { name: 'Attendee로 입장' }).click()
    await expect(attendee.getByTestId('connection-status')).toHaveText('실시간 연결')
    await expect(attendee.locator('.room-capacity')).toContainText('실제 참여 2명 · 예시 관객 8명')
    await expect(attendee.getByTestId('question-card')).toHaveCount(3)
    await expect(page.getByTestId('person-row')).toHaveCount(10)
    await expect(attendee.getByTestId('question-bubble')).toHaveCount(0)
  } finally { await attendee.close() }
})

test('public question bubbles follow seated and walking avatars and keep AI chat private', async ({ page, browser }) => {
  test.setTimeout(60_000)
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('/')
  await page.getByLabel('참여 이름', { exact: true }).fill('발표자')
  await page.getByRole('button', { name: 'Host로 방 열기' }).click()
  await expect(page.getByTestId('connection-status')).toHaveText('실시간 연결')
  const attendee = await browser.newPage()
  attendee.on('pageerror', (error) => errors.push(error.message))
  try {
    await attendee.goto(page.url())
    await attendee.getByLabel('참여 이름', { exact: true }).fill('질문하는 팀원')
    await attendee.getByRole('button', { name: 'Attendee로 입장' }).click()
    await expect(attendee.getByTestId('connection-status')).toHaveText('실시간 연결')
    for (const client of [page, attendee]) {
      await client.clock.install({ time: new Date('2026-01-01T00:00:00Z') })
      await client.clock.pauseAt(new Date('2026-01-01T00:00:01Z'))
    }
    await expect(attendee.getByTestId('question-bubble')).toHaveCount(0)
    await attendee.getByTestId('seat-18').click()
    await attendee.getByLabel('발표자에게 질문하기').fill('앉아서 질문해도 모두에게 보이나요?')
    await attendee.locator('.question-form button[type="submit"]').click()
    const ownBubble = attendee.getByTestId('question-bubble').filter({ hasText: '질문하는 팀원' })
    await expect(ownBubble).toContainText('앉아서 질문해도 모두에게 보이나요?')
    await expect(ownBubble).toHaveClass(/is-seated.*is-me/)
    await expect(page.getByTestId('question-bubble')).toContainText('앉아서 질문해도 모두에게 보이나요?')
    const bubbleBox = await ownBubble.boundingBox()
    const avatarBox = await attendee.locator('.my-seat .seated-avatar').boundingBox()
    expect(bubbleBox && avatarBox && bubbleBox.y + bubbleBox.height < avatarBox.y).toBe(true)

    await attendee.getByRole('button', { name: '자리에서 일어나 둘러보기' }).click()
    await expect(ownBubble).toHaveClass(/is-standing/)
    const before = await ownBubble.evaluate((element) => (element as HTMLElement).style.left)
    const scene = attendee.getByTestId('theater-scene')
    const sceneBox = await scene.boundingBox()
    if (!sceneBox) throw new Error('The theater must be visible to move the avatar')
    await scene.click({ position: { x: sceneBox.width * .62, y: sceneBox.height * .76 } })
    await expect.poll(() => ownBubble.evaluate((element) => (element as HTMLElement).style.left)).not.toBe(before)

    await page.getByLabel('발표자에게 질문하기').fill('발표자 질문도 캐릭터 위에 보여요.')
    await page.locator('.question-form button[type="submit"]').click()
    await expect(attendee.getByTestId('question-bubble')).toHaveCount(2)
    await attendee.getByRole('button', { name: 'AI 질문 도우미 열기' }).click()
    await attendee.getByLabel('AI 도우미에게 질문하기').fill('나만 볼 비공개 질문')
    await attendee.locator('.ai-chat-form button[type="submit"]').click()
    await expect(attendee.locator('.ai-chat-bubble.user')).toContainText('나만 볼 비공개 질문')
    await expect(page.getByTestId('question-bubble')).toHaveCount(2)
    await expect(page.locator('.avatar-question-layer')).not.toContainText('나만 볼 비공개 질문')
    await attendee.getByRole('button', { name: 'AI 질문 도우미 닫기' }).click()

    await attendee.getByLabel('발표자에게 질문하기').fill('새 질문이 이전 말풍선을 바꿔요.')
    await attendee.locator('.question-form button[type="submit"]').click()
    await expect(ownBubble).toContainText('새 질문이 이전 말풍선을 바꿔요.')
    await expect(attendee.getByTestId('question-bubble')).toHaveCount(2)
    await expect(ownBubble).not.toContainText('앉아서 질문해도 모두에게 보이나요?')
    await attendee.screenshot({ path: 'test-results\\avatar-question-bubbles.png', fullPage: true })
    await attendee.setViewportSize({ width: 390, height: 844 })
    expect(await attendee.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    const mobileBubble = await ownBubble.boundingBox()
    const mobileScene = await scene.boundingBox()
    expect(mobileBubble && mobileScene && mobileBubble.x >= mobileScene.x
      && mobileBubble.x + mobileBubble.width <= mobileScene.x + mobileScene.width).toBe(true)
    await attendee.screenshot({ path: 'test-results\\avatar-question-bubbles-mobile.png', fullPage: true })

    for (const client of [page, attendee]) {
      await client.clock.fastForward(13_000)
      await expect(client.getByTestId('question-bubble')).toHaveCount(0)
    }
    await page.getByTestId('question-card').filter({ hasText: '새 질문이 이전 말풍선을 바꿔요.' })
      .getByRole('button', { name: /질문에 공감/ }).click()
    await expect(page.getByTestId('question-bubble')).toHaveCount(0)
    await expect(attendee.getByTestId('question-bubble')).toHaveCount(0)
    const lateAttendee = await browser.newPage()
    try {
      await lateAttendee.goto(page.url())
      await lateAttendee.getByRole('button', { name: 'Attendee로 입장' }).click()
      await expect(lateAttendee.getByTestId('connection-status')).toHaveText('실시간 연결')
      await expect(lateAttendee.getByTestId('question-card')).toHaveCount(6)
      await expect(lateAttendee.getByTestId('question-bubble')).toHaveCount(0)
    } finally { await lateAttendee.close() }
    expect(errors).toEqual([])
  } finally { await attendee.close() }
})
